### ISSUE TITLE
Update migration guide

### ISSUE THREAD

**Issue by itsjoekent** [prismicio/prismic-client#213]
Hello! The migration guide for `resolvePreviewURL` included a token in the v5 example, but omitted it in the v6 example. I assumed that was intentional but turned out that accidentally broke our previews! Just wanted to flag the documentation should be updated so both examples include the token.

![image](https://user-images.githubusercontent.com/897368/151611277-eb196306-0f56-49a9-b0b7-e5b15e120272.png)

**Comment by angeloashmore** [comment]
Hey @itsjoekent, this is actually intentional like you assumed 🙂 (but of course, it's supposed to work automatically). `resolvePreviewURL()` should read `globalThis.location.search` for the `token` and `documentId` URL params without needing to pass them manually.

Could you share some details about where you're using `resolvePreviewURL()`? Is there anything unique about the setup? Such as being on a server or in a specific browser?

For reference, the following preview-related methods are available on a client:

- **`client.enableAutoPreviews()`** - Configures the client to automatically query content from a preview session. This is the client's default mode.
- **`client.enableAutoPreviewsFromReq(req)`** - Accepts a server request object containing the request's headers and cookies. Configures the client to automatically query content from a preview session in a server environment.
- **`client.disableAutoPreviews()`** - Configures the client to ignore preview sessions. Queries will be made against the latest published content or the client's configured release.

Source: https://prismic.io/docs/technical-reference/prismicio-client#repo-methods

You can still provide `documentID` and `previewToken` as parameters to `resolvePreviewURL()` if you need to provide them manually for some reason (such as not being in a browser or Express server-like environment).

<details>
<summary><strong>Here's the relevant code in case you are curious</strong></summary>

https://github.com/prismicio/prismic-client/blob/b141ba78c7f842b4c147419f6d7f26ac3b2bb125/src/client.ts#L1155-L1165
</details>

Thanks!

**Comment by itsjoekent** [comment]
Hi @angeloashmore ! Thanks for that, like I mentioned in the original description, the specific thing I got hung-up on was that the example appears to show the token being intentionally removed (that screenshot is from the migration guide [here](https://prismic.io/docs/technologies/prismic-client-v6-migration-guide#replace-getpreviewresolver-with-resolvepreviewurl).

![Screen Shot 2022-01-31 at 2 20 13 PM](https://user-images.githubusercontent.com/897368/151858786-de94b12b-dc98-44fe-aa30-306062c0e361.png)

I realize your overall point however that it's supposed to be "automatic", maybe just drop a note in the migration guide that Node environments should still keep the token?

**Comment by angeloashmore** [comment]
Ah, good point. Yes, a note should be added there like you described. I'll work on getting that updated. 👍

**Comment by angeloashmore** [comment]
@itsjoekent Thanks again for the suggestion. The migration guide now explains how to upgrade in Express and non-Express server environments.

https://prismic.io/docs/technologies/prismic-client-v6-migration-guide#replace-getpreviewresolver-with-resolvepreviewurl

I'm going to close this issue, but please let me know if you think there's a better way to describe this. Thanks!
