### ISSUE TITLE
client.getTags() is broken. 

### ISSUE THREAD

**Issue by akumanara** [prismicio/prismic-client#243]
client.getTags() returns an empty array and i had to use the following to get the tags.

Replace my-repo-name with your repo name.

const url = new URL('https://my-repo-name.cdn.prismic.io/api/tags');
  url.searchParams.set('access_token', client.accessToken);
  let test = await client.fetch(url.toString());

**Comment by angeloashmore** [comment]
Hi @akumanara, apologies on the delay for a response. Thanks for reporting the issue and providing your workaround. It highlighted that the `getTags()` method was not properly sending the client's `accessToken` parameter to the Tags API endpoint.

This should be fixed as of #245. The fix is not published yet, but it will be included in the next version.
