### ISSUE TITLE
Provide better Typescript definition files

### ISSUE THREAD

**Issue by nimaen** [prismicio/prismic-client#27]
Hi Prismic folks :)

I'm trying to use the nodejs package with its bundled d.ts files.
However, types are not properly imported when using the module.
It comes from several facts:
- First, this comes from the way the module is declared, ie. using a namespace. `declare namespace Prismic {...}` & `export = Prismic;`. Only what is in the namespace is visible if i'm not mistaken.
- As a library, the barel file (index.d.ts) should re-export all public APIs. When fetching the api object with `Prismic.getApi(...)`, I cannot write the proper response type since the `PrismicApi` type is hidden in the namespace.

It could be better to change the namespace to a plain object while re-exporting all sub modules. This way, both the Prismic object and all APIs are visible.

Last but not the least, a little quote from the TS documentation :

> Exporting a namespace from your module is an example of adding too many layers of nesting. While namespaces sometime have their uses, they add an extra level of indirection when using modules. This can quickly become a pain point for users, and is usually unnecessary.

What do you guys think ?

**Comment by deroude** [comment]
with Angular 5 I get an outright error: 
`ERROR in src/app/prismic/prismic.service.ts(3,8): error TS1192: Module '"/node_modules/prismic-javascript/d.ts/index"' has no default export.`

**Comment by levimykel** [comment]
Hi @nimaen, sorry for the delay but we will try our best to look at this as soon as we are able.

**Comment by mattiascibien** [comment]
I agree. Interfaces and Classes cannot be imported and it could be nice to have them exported in order not to keep using `any` everywhere (including the api client)

**Comment by jwldnr** [comment]
@mattiascibien but this violates the `tslint` rule `no-submodule-imports`:

![tt](https://user-images.githubusercontent.com/11960421/42508386-97c34936-8448-11e8-93cd-c2fad911d747.png)

**Comment by shyamal890** [comment]
+1

**Comment by FibHeap** [comment]
with typescript > 2.8 this should work

```
import * as Prismic from 'prismic-javascript'

type ThenArg<T> = T extends Promise<infer U> ? U : T
type PrismicAPIPromise = ReturnType<typeof Prismic.getApi>
type PrismicAPI = ThenArg<PrismicAPIPromise>
```

**Comment by evolkmann** [comment]
Unfortunately this is still open. I guess the issue could be resolved for many of us if `d.ts/index.d.ts` would also export the other parts of the declaration files, for example `ResolvedApi.d.ts`.

Now with Angular 9, the compiler issues a warning about the deep import paths, for example here: https://github.com/exportarts/ngx-prismic/issues/109.

I wonder if there is even still the need for separate `d.ts` files since the project is written in typescript anyway. What do you think?

**Comment by heavybeard** [comment]
Any updates here?

**Comment by pmourer** [comment]
The example here: https://prismic.io/docs/reactjs/getting-started/prismic-nextjs#28_0-pass-the-preview-ref-to-all-of-your-pages even throws type errors. Is there any plans to get things lined up?

**Comment by carperbr** [comment]
Perhaps this could be a naive approach, but I encountered this issue as well. I modified the types/index.d.ts accordingly in order to successfully use Prismic 3.0.2 with typescript. [Here is a gist](https://gist.github.com/carperbr/a3359d65cbb404e28cf5ba24c468d4a3) with the updated file that I'm using. and I import it using `import * as Prismic from "prismic-javascript"`

If anyone has any suggestions for making that more correct please chime in!

**Comment by carperbr** [comment]
If anyone is interested, I made some modifications to the index.d.ts definitions in order to use Prismic 3.0.2 with typescript. [Here is a gist](https://gist.github.com/carperbr/a3359d65cbb404e28cf5ba24c468d4a3) of my changes. You can use it in a couple ways. You an import everything via `import * as Prismic from 'prismic-javascript'` and then do the usual instantiation with `Prismic.client(...)` and query via `client.query(Prismic.Predicates.at("document.type", "blog01"))`, or you can import just what you need like `import { client, Predicates } from 'prismic-javascript'`

Hopefully this helps people, and if anyone has suggestions on making it cleaner please let me know!

**Comment by DaSchTour** [comment]
When using `import * as Prismic from 'prismic-javascript'` types are not correctly detected and when using `import Prismic from 'prismic-javascript'` I get undefined errors. Why not simply use named exports? From my experience default exports are a very bad practice that lead to a lot of problems.

**Comment by lihbr** [comment]
Hey @DaSchTour, I'm sorry you ran into those issues, we're aware that TypeScript support is not ideal right now on this package.

Great news though, we're currently working on the next major of our JavaScript SDK, improving TypeScript support being one of the goals there. An alpha should land in the coming weeks, in the meantime you can stay tuned to #163 🙂

**Comment by lihbr** [comment]
Hey! Just letting you all know that @prismicio/client v6 has since been published in alpha 🎉

It's not documented yet but the API is pretty similar, now comes with built-in tsdoc and beautiful TypeScript support, we also have examples :)

https://github.com/prismicio/prismic-javascript/tree/aa/v6/examples

It will land in stable/lastest once properly documented and tested on our side!

**Comment by lihbr** [comment]
Fixed in v6 🎉 Thank you for your contribution!

https://prismic.io/docs/technical-reference/prismicio-client?version=v6
