### ISSUE TITLE
`routes` parameter doesn't resolve properly

### ISSUE THREAD

**Issue by dturkington49** [prismicio/prismic-client#320]
### Versions

- @prismicio/client: 7.1.1
- node: 18.16.0

### Reproduction

```
const routes = [
  {
    type: 'standard_landing_page',
    resolvers: {
      parent: 'parent_id',
      grandParentId: 'parent_id.parent_id',
    },
    path: '/:grandParentId/:parent/:uid/',
  },
];

const prismicClient = prismic.createClient("xometry-marketing", { routes });

await prismicClient.get({
  page: 4, 
  pageSize: 100,
  routes,
  filters: [
    prismic.filter.any('document.type', [
      'standard_landing_page',
    ])
  ]
});

```

The client attempts to query the following URL:

https://xometry-marketing.cdn.prismic.io/api/v2/documents/search?q=%5B%5Bany%28document.type%2C+%5B%22standard_landing_page%22%5D%29%5D%5D&page=2&pageSize=20&ref=ZO5XOBEAACQAiq8v&routes=%5B%7B%22type%22%3A%22standard_landing_page%22%2C%22resolvers%22%3A%7B%22parent%22%3A%22parent_id%22%2C%22grandParentId%22%3A%22parent_id.parent_id%22%7D%2C%22path%22%3A%22%2F%3AgrandParentId%2F%3Aparent%2F%3Auid%2F%22%7D%5D

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

Run the code above.

### What is expected?

A full paginated set of results

### What is actually happening?

500 error with no error message

**Comment by lihbr** [comment]
Hey there, thanks for opening an issue!

It looks like the above URL requires an access token so I'm not able to test it.

That kind of issue usually happens when the grandparent doesn't have a `parent_id` field.
The route resolver is only able to resolve parent/grandparent if the content relationship they rely on is linking to one custom type type.

Could you share more information about your content modelling setup?
Also, can you try adding question marks to the parent and grandparent placeholders? This could help troubleshoot your issue:
```bash
path: '/:grandParentId?/:parent?/:uid/'
```

**Comment by lihbr** [comment]
Hey @dturkington49, OK, I think I managed to pinpoint it.

The query is failing because [this document](https://xometry-marketing.cdn.prismic.io/api/v2/documents/search?q=%5B%5Bany%28document.type%2C+%5B%22standard_landing_page%22%5D%29%5D%5D&page=31&pageSize=1&ref=ZO-K_hEAACYAkB_g) has as a parent page [the "home" document](https://xometry-marketing.cdn.prismic.io/api/v2/documents/search?q=%5B%5Bany%28document.type%2C+%5B%22home%22%5D%29%5D%5D&ref=ZO-K_hEAACYAkB_g) which doesn't contain a `parent_id` field, making [the query with the routes parameter](https://xometry-marketing.cdn.prismic.io/api/v2/documents/search?q=%5B%5Bany%28document.type%2C+%5B%22standard_landing_page%22%5D%29%5D%5D&page=31&pageSize=1&ref=ZO-K_hEAACYAkB_g&routes=%5B%7B%22type%22%3A%22standard_landing_page%22%2C%22resolvers%22%3A%7B%22parent%22%3A%22parent_id%22%2C%22grandParentId%22%3A%22parent_id.parent_id%22%7D%2C%22path%22%3A%22%2F%3AgrandParentId%3F%2F%3Aparent%3F%2F%3Auid%2F%22%7D%5D) fail.

It should work fine if you allow the "home" document a `parent_id` field (even if it remains empty forever, you can tuck it under a dedicated tab to hide it). Let me know if that does the trick for you!

I also acknowledge the error is silly and the API should be clearer, I'll relay that to our platform team.

**Comment by dturkington49** [comment]
Good morning @lihbr, I removed the home document from the parent_id relationship and made the API respond with a 200 as expected! Additionally, I needed to add the ? characters to the optional segments in route path. So my final result is

`const routes = [
  {
    type: 'standard_landing_page',
    resolvers: {
      parentId: 'parent_id',
      grandparentId: 'parent_id.parent_id',
    },
    path: '/:grandparentId?/:parentId?/:uid/',
  },
];`
