### ISSUE TITLE
Typescript is missing next property in fetchOptions

### ISSUE THREAD

**Issue by vvopenka** [prismicio/prismic-client#329]
### Versions

- @prismicio/client: 7.3.1
- node: 18.17.1

### Reproduction

When I'm trying to initialize client acoarding to the documentation: https://prismic.io/docs/fetch-data-nextjs#caching-with-the-app-router 
```Typescript
const client = prismic.createClient("RepoName", {
      accessToken: process.env.PRISMIC_ACCESS_TOKEN,
      fetchOptions: {
        next: { revalidate: 5 }
      }
    });
```

I keep on getting an error: Type '{ next: { revalidate: number; }; }' is not assignable to type 'RequestInitLike'.

It seems like it's missing in the type: https://github.com/prismicio/prismic-client/blob/bd5507167fc42054e16999e6046c2567e86a190b/src/createClient.ts#L113

Would it be possible to add it? Or is there a way to define next.revalidate in typescript?

### Steps to reproduce
Create a client using the documentation in next.js in typescript.
```Typescript
const client = prismic.createClient("RepoName", {
      accessToken: process.env.PRISMIC_ACCESS_TOKEN,
      fetchOptions: {
        next: { revalidate: 5 }
      }
    });
```
### What is expected?
I should be able to define next.revalidate and next.tags.

### What is actually happening?
The code above fails to compile in typescript.

**Comment by angeloashmore** [comment]
Hi @vvopenka, the `next` options are specific to Next.js, so we'd like to keep it out of the general `@prismicio/client` package.

Luckily, installing `@prismicio/next` and using it in your project will fix this issue ([see these lines of code](https://github.com/prismicio/prismic-next/blob/df6fda8f2794bde0bd646ae85704de65a2ee02ec/src/types.ts#L4-L9)). `@prismicio/next` should be used in your Next.js project for content previews, `<PrismicNextLink>`, and `<PrismicNextImage>`.

You can find documentation for `@prismicio/next` here: https://prismic.io/docs/technical-reference/prismicio-next

Could you give that a try and let me know if that fixes the issue? I'm going to close this issue since it should be working, but we can re-open it if the issue still exists.
