### ISSUE TITLE
SyntaxError: Named export 'whitespace' not found. The requested module './../_node_modules/hast-util-whitespace/lib/index.js'

### ISSUE THREAD

**Issue by radaalinmihai** [prismicio/prismic-client#344]
### Versions

- @prismicio/client: v7.7.3
- node: v20.11.0

### Reproduction

The reproduction is simple, install the latest version, which is 7.7.3 on any project and you will be greeted with an error:
<img width="960" alt="image" src="https://github.com/user-attachments/assets/31e156e2-7c1c-470a-815f-1faebf648144">

### Steps to reproduce

1. Create any new project which utilizez @prismic/client@^7.7.3
2. Run project
3. Be greeted with error from Reproduction section

### What is expected?
No error to be shown

### What is actually happening?
Error is shown.

**Edit:**
On further investigation I think it has something to do with this file: https://github.com/prismicio/prismic-client/blob/master/src/lib/hastToRichText.ts#L2 specifically with that external package 'hast-util-whitespace'

**Comment by lihbr** [comment]
Hey @radaalinmihai, thanks for voicing your issue, we're aware of the issue with the latest released and are investigating it.

A fix will be released today.

**Comment by lihbr** [comment]
Hi there,

Once again, thank you so much for reporting this issue and trying out the latest version of our kit!

This should now be fixed in `@prismicio/client` v7.7.4, update with:

```bash
npm update @prismicio/client
```

I'm gonna close this issue as everything checked in our QA process. If you still experience the issue with the latest version, you're very welcome to reopen this issue!

Thanks again 🙏

**Comment by radaalinmihai** [comment]
Thanks again for the promptness and your speed in fixing this issue! Have a good day!
